type Idea = { name:string; category:string; target:string; effectType:string; amount:number; copies:number; officialDescription:string; commissionerNotes:string; isSpecial?:boolean }

const basic = (category:string,name:string,amount:number,target:string,copies:number):Idea => ({
  name,category:category==='DEFENSE'?'UNIQUE':category,target,copies,amount,isSpecial:category==='DEFENSE',effectType:category==='ATTACK'?'Percentage reduction':category==='DEFENSE'?'Attack protection':'Percentage boost',
  officialDescription:category==='ATTACK'?`Reduce your opponent's starting ${target} points by ${amount}%.`:category==='DEFENSE'?`Reduce an incoming attack against your ${target} by ${amount}%.`:`Increase your starting ${target} points by ${amount}%.`,
  commissionerNotes:'Imported from the Card Data sheet. Effect follows the indicated lineup position.'
})
const special = (name:string,target:string,amount:number,copies:number,officialDescription:string,notes=''):Idea => ({name,category:'UNIQUE',target,amount,copies,isSpecial:true,effectType:'Specialty rule',officialDescription,commissionerNotes:`Imported from the Card Data sheet. ${notes}`.trim()})

export const cardDataIdeas: Idea[] = [
  basic('ATTACK','Edge Rush',25,'QB',3),basic('ATTACK','Swim Move',50,'QB',2),basic('ATTACK','Bull Rush',100,'QB',1),
  basic('ATTACK','Iron Curtain',25,'RB',3),basic('ATTACK','Stacked Box',50,'RB',2),basic('ATTACK','Stuffed',100,'RB',1),basic('ATTACK','Lockdown',25,'WR',3),basic('ATTACK','Double Teamed',50,'WR',2),basic('ATTACK','No Fly Zone',100,'WR',1),basic('ATTACK','Shutdown',25,'TE',3),basic('ATTACK','Pressure',50,'TE',2),basic('ATTACK','The Mike',100,'TE',1),
  basic('BOOST','Launched',25,'QB',3),basic('BOOST','Air It Out',50,'QB',2),basic('BOOST','West Coast',100,'QB',1),basic('BOOST','Stiff Arm',25,'RB',3),basic('BOOST','Ankle Breaker',50,'RB',2),basic('BOOST','Trucked',100,'RB',1),basic('BOOST','Crosser',25,'WR',3),basic('BOOST','Deep Threat',50,'WR',2),basic('BOOST',"Moss'd",100,'WR',1),basic('BOOST','Possession',25,'TE',3),basic('BOOST',"Shake'n'Bake",50,'TE',2),basic('BOOST','Gronk',100,'TE',1),
  special('Challenge Flag','Opponent card',0,1,"After Wednesday's reveal, cancel one player-played opponent card before Thursday kickoff.",'Opening supply automatically matches the number of teams.'),
  special('Pick Six','QB/DEF',2,2,"Remove the opponent QB's passing-touchdown points and give them to your defense."),special('Complete','QB',2,2,'Add 2 extra points for every completion by your QB.'),special('Incomplete','QB',3,2,'Add 3 extra points for every incompletion by your QB.'),special('Rough Start','Opponent starter',-20,2,'Start one opponent player at minus 20 points.'),special('Double TD','Chosen Player',100,2,"Double one player's touchdown points this week."),special('Double or Nothing','W/R/T',100,2,'Five or more catches doubles the player’s score. Four or fewer scores zero.'),
  special('Bromance','QB',100,2,"Use double Patrick Mahomes's score as your QB score, regardless of your starter."),special('Spygate','Opponent starter',0,2,"Replace one opponent starter with a healthy, same-slot-eligible bench player."),special('Traded WR','Weekly opponent WR',0,2,"Use a weekly opponent WR to replace an eligible player in your lineup."),special('Traded RB','Weekly opponent RB',0,2,"Use a weekly opponent RB to replace an eligible player in your lineup."),special('Traded TE','Weekly opponent TE',0,2,"Use a weekly opponent TE to replace an eligible player in your lineup."),special('FAFB','QB',100,2,"Double your QB's rushing-yard points this week."),special('Sticky Hands','W/R/T',2,2,'Every reception by the chosen player is worth 2 points.'),special('Beast Mode','RB',0.3,2,'Every rushing yard by your RB is worth 0.3 points.'),special('Sacked','Opponent QB',-5,2,'Subtract 5 points every time the targeted QB is sacked.'),basic('BOOST','Shoestring Tackle',50,'DEF',2),special('Big Sack','DEF',5,2,'Every sack by your defense is worth 5 total points.'),special('Interception','DEF',15,2,'Every interception by your defense is worth 15 total points.'),special("Aaaaaand Nobody's Blocking",'QB',5,2,'Add 5 points each time your starting QB is sacked.'),special('28-3','Team',51,2,'If you trail by 50 or more entering Monday night, add exactly 51 points.'),special('Medical Tent','Team',50,2,'If a starter scores below 5 and is listed Out or IR Tuesday morning, add 50 points.'),special('Butt Fumble','Your starters',10,2,'Add 10 points for every fumble by your starting lineup.'),special('2025 Derrick Henry','Opponent starters',-10,2,'Subtract 10 points for every fumble by the opponent starting lineup.'),special('Big Hit','Opponent starter',10,2,'Cap one opponent starter at 10 points.'),special('Cap Hit','Opponent team',15,2,'Cap every opposing starter at 15 points.'),special('MVP','Your starter',0,2,"Replace your lowest same-position starter with the league's highest-scoring starter."),special('1v1 me bro','Any position',0,2,'The higher matching-position starter earns both scores; the card owner wins a tie.'),special('Immaculate Reception','W/R/T',15,2,'Catch every target with at least 3 targets to add 15 points.')
]

export const toDraftRequest = (idea:Idea) => ({...idea,rarity:idea.isSpecial?'Specialty':'Common',artworkUrl:'',submitForReview:false})
