type Idea = { name:string; category:string; target:string; effectType:string; amount:number; copies:number; officialDescription:string; commissionerNotes:string; isSpecial?:boolean }

const basic = (category:string,name:string,amount:number,target:string,copies:number):Idea => ({
  name,category,target,copies,amount,isSpecial:false,effectType:category==='ATTACK'?'Percentage reduction':category==='DEFENSE'?'Attack protection':'Percentage boost',
  officialDescription:category==='ATTACK'?`Reduce your opponent's starting ${target} points by ${amount}%.`:category==='DEFENSE'?`Reduce an incoming attack against your ${target} by ${amount}%.`:`Increase your starting ${target} points by ${amount}%.`,
  commissionerNotes:'Imported from the Card Data sheet. Effect follows the indicated lineup position.'
})
const special = (name:string,target:string,amount:number,copies:number,officialDescription:string,notes=''):Idea => ({name,category:'BOOST',target,amount,copies,isSpecial:true,effectType:'Specialty rule',officialDescription,commissionerNotes:`Imported from the Card Data sheet. ${notes}`.trim()})

export const cardDataIdeas: Idea[] = [
  basic('ATTACK','Two Deep',25,'QB',3),basic('ATTACK','No Fly Zone',50,'QB',2),basic('ATTACK','Air Traffic Control',100,'QB',1),
  basic('DEFENSE','Iron Curtain',25,'RB',3),basic('DEFENSE','Stacked Box',50,'RB',2),basic('DEFENSE','Stuffed',100,'RB',1),basic('DEFENSE','Lockdown',25,'WR',3),basic('DEFENSE','Double Teamed',50,'WR',2),basic('DEFENSE','Denial',100,'WR',1),basic('DEFENSE','Shutdown',25,'TE',3),basic('DEFENSE','Pressure',50,'TE',2),basic('DEFENSE','The Mike',100,'TE',1),
  basic('BOOST','Launched',25,'QB',3),basic('BOOST','Air It Out',50,'QB',2),basic('BOOST','West Coast',100,'QB',1),basic('BOOST','Stiff Arm',25,'RB',3),basic('BOOST','Ankle Breaker',50,'RB',2),basic('BOOST','Trucked',100,'RB',1),basic('BOOST','Crosser',25,'WR',3),basic('BOOST','Deep Threat',50,'WR',2),basic('BOOST',"Moss'd",100,'WR',1),basic('BOOST','Possession',25,'TE',3),basic('BOOST',"Shake'n'Bake",50,'TE',2),basic('BOOST','Gronk',100,'TE',1),
  special('Challenge Flag','N/A',0,10,"Stop one opponent's card from being played or scored.",'One card per team at the start of the season.'),
  special('Pick Six','QB/DEF',2,2,"Remove the opponent QB's touchdown points and give them to your defense."),special('Complete','QB',2,2,'Add 2 points for every completion by your QB.'),special('Incomplete','QB',3,2,'Add 3 points for every incompletion by your QB.'),special('Rough Start','Single Player',15,2,'Start one opponent player at minus 15 points.'),special('Double TD','Chosen Player',100,2,"Double one player's touchdown points this week."),special('Double or Nothing','W/R/T',100,2,'Five or more catches doubles the player’s score. Four or fewer scores zero.'),
  special('Bromance','QB',100,2,"Use double Patrick Mahomes's score as your QB score, regardless of your starter."),special('Spygate','Chosen Player',0,2,"Replace one opponent starter with a bench player you choose.",'The replacement cannot be injured.'),special('Traded WR','Chosen Player',0,2,"Use another team's WR score in your starting lineup."),special('Traded RB','Chosen Player',0,2,"Use another team's RB score in your starting lineup."),special('Traded TE','Chosen Player',0,2,"Use another team's TE score in your starting lineup."),special('FAFB','QB',100,2,"Double your QB's rushing-yard points this week."),special('Sticky Hands','W/R/T',2,2,'Every reception by the chosen player is worth 2 points.'),special('Beast Mode','RB',0.3,2,'Every rushing yard by your RB is worth 0.3 points.'),special('Sacked','QB',-5,2,'Subtract 5 points every time the targeted QB is sacked.'),special('Shoestring Tackle','Defense',50,2,'Apply a 50% effect to defense scoring.','Confirm whether this increases or reduces points.'),special('28-3','Team',40,2,'If you trail by 50 or more entering Monday night, add 40 points after the week.'),special('Injured','Team',50,2,'If one of your starters is injured and does not return, add 50 points.'),special('Butt Fumble','Team',5,2,'Add 5 points each time a player on your team fumbles.'),special('Cap Hit','Team',15,2,'Cap every opposing player at 15 points.'),special('MVP','Chosen Player',0,2,"Use the league's highest-scoring player in your lineup.",'Choose the destination slot before final approval.'),special('1v1 me bro','ALL',0,2,'Choose a position. The winner of the two chosen players earns both scores.')
]

export const toDraftRequest = (idea:Idea) => ({...idea,rarity:idea.isSpecial?'Specialty':'Common',artworkUrl:'',submitForReview:false})
