-- Fantasy Football Chaos Cards - PostgreSQL 16+
-- All IDs are generated by the application. Store timestamps in UTC.
begin;

create table chaos_leagues (
    id uuid primary key,
    sleeper_league_id text not null unique,
    name text not null,
    commissioner_user_id text not null,
    timezone text not null default 'America/Indianapolis',
    max_hand_size smallint not null default 5 check (max_hand_size between 1 and 20),
    max_preweek_cards smallint not null default 2 check (max_preweek_cards between 0 and 10),
    max_live_cards smallint not null default 1 check (max_live_cards between 0 and 10),
    created_at timestamptz not null default now()
);

create table chaos_teams (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    sleeper_roster_id integer not null,
    owner_user_id text,
    sleeper_owner_id text,
    name text not null,
    avatar_url text,
    created_at timestamptz not null default now(),
    unique (league_id, sleeper_roster_id),
    unique (league_id, owner_user_id)
);

create table league_memberships (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    user_id text not null,
    team_id uuid references chaos_teams(id),
    status text not null default 'active' check (status in ('invited','active','suspended','removed')),
    is_primary_commissioner boolean not null default false,
    invited_by_user_id text,
    invited_at timestamptz,
    joined_at timestamptz,
    unique (league_id, user_id),
    unique (league_id, team_id)
);

-- Exactly one active primary commissioner per league.
create unique index ux_one_primary_commissioner
    on league_memberships (league_id)
    where is_primary_commissioner = true and status = 'active';

create table member_permissions (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    user_id text not null,
    permission text not null check (permission in (
        'create_card_drafts','edit_card_rules','approve_cards','manage_deck','invite_managers','assign_rosters','manage_deadlines',
        'lock_weeks','correct_scores','view_private_hands','manage_co_commissioners'
    )),
    granted_by_user_id text not null,
    granted_at timestamptz not null default now(),
    revoked_by_user_id text,
    revoked_at timestamptz,
    foreign key (league_id, user_id) references league_memberships(league_id, user_id),
    check ((revoked_at is null and revoked_by_user_id is null) or
           (revoked_at is not null and revoked_by_user_id is not null))
);

create unique index ux_active_member_permission
    on member_permissions (league_id, user_id, permission)
    where revoked_at is null;

create table card_definitions (
    id uuid primary key,
    name text not null,
    workflow_status text not null default 'idea' check (workflow_status in ('idea','artwork_ready','needs_review','active','archived')),
    category text not null check (category in ('attack','boost','defense')),
    rarity text not null default 'common',
    is_special boolean not null default false,
    official_description text not null default '',
    artwork_key text,
    commissioner_notes text not null default '',
    target_type text not null check (target_type in ('starting_slot','position_group','team','specific_player','dynamic')),
    effect_type text not null check (effect_type in ('flat_points','percentage','block_attack','reduce_attack','referenced_player_replaces_slot','custom')),
    effect_amount numeric(12,4) not null default 0,
    referenced_player_id text,
    destination_slot text,
    multiplier numeric(12,4),
    custom_handler text,
    is_active boolean not null default false,
    reviewed_by_user_id text,
    reviewed_at timestamptz,
    created_by_user_id text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (workflow_status not in ('needs_review','active') or artwork_key is not null),
    check (workflow_status <> 'active' or (is_active = true and reviewed_by_user_id is not null and reviewed_at is not null)),
    check (workflow_status <> 'active' or effect_type <> 'referenced_player_replaces_slot' or
        (referenced_player_id is not null and destination_slot is not null and multiplier is not null)),
    check (effect_type <> 'custom' or custom_handler is not null)
);

create table card_copies (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    definition_id uuid not null references card_definitions(id),
    state text not null check (state in ('deck','hand','secret_selection','locked','revealed','played','weekly_discard')),
    owner_team_id uuid references chaos_teams(id),
    current_week_id uuid,
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    check ((state in ('hand','secret_selection','locked','revealed','played') and owner_team_id is not null)
        or (state in ('deck','weekly_discard') and owner_team_id is null))
);

create index ix_card_copies_deck on card_copies (league_id, definition_id) where state = 'deck';
create index ix_card_copies_hand on card_copies (league_id, owner_team_id) where state = 'hand';

create table chaos_weeks (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    season integer not null,
    week_number smallint not null check (week_number between 1 and 25),
    status text not null check (status in ('setup','selection_open','locked','revealed','live','finalized')),
    selection_deadline timestamptz not null,
    locked_at timestamptz,
    revealed_at timestamptz,
    finalized_at timestamptz,
    unique (league_id, season, week_number)
);

alter table card_copies add constraint fk_card_copy_week foreign key (current_week_id) references chaos_weeks(id);

create table chaos_matchups (
    id uuid primary key,
    week_id uuid not null references chaos_weeks(id),
    sleeper_matchup_id integer,
    team_a_id uuid not null references chaos_teams(id),
    team_b_id uuid not null references chaos_teams(id),
    sleeper_score_a numeric(12,4),
    sleeper_score_b numeric(12,4),
    chaos_score_a numeric(12,4),
    chaos_score_b numeric(12,4),
    winner_team_id uuid references chaos_teams(id),
    finalized_calculation jsonb,
    finalized_at timestamptz,
    check (team_a_id <> team_b_id),
    unique (week_id, team_a_id),
    unique (week_id, team_b_id)
);

create table card_plays (
    id uuid primary key,
    week_id uuid not null references chaos_weeks(id),
    matchup_id uuid not null references chaos_matchups(id),
    team_id uuid not null references chaos_teams(id),
    card_copy_id uuid not null references card_copies(id),
    timing text not null check (timing in ('preweek','live')),
    target_type text not null,
    target_team_id uuid not null references chaos_teams(id),
    target_starting_slot text,
    target_position text,
    target_nfl_player_id text,
    target_dynamic_rule text,
    selected_at timestamptz not null,
    locked_at timestamptz,
    revealed_at timestamptz,
    played_at timestamptz,
    returned_to_hand_at timestamptz,
    check (not (played_at is not null and returned_to_hand_at is not null))
);

-- Active-only limits. Returned selections no longer count.
create unique index ux_one_live_play_per_team_week
    on card_plays (week_id, team_id)
    where timing = 'live' and returned_to_hand_at is null;

create unique index ux_one_active_play_per_card_week
    on card_plays (week_id, card_copy_id)
    where returned_to_hand_at is null;

create table lineup_snapshots (
    id uuid primary key,
    week_id uuid not null references chaos_weeks(id),
    team_id uuid not null references chaos_teams(id),
    captured_at timestamptz not null,
    source text not null default 'sleeper',
    slots jsonb not null,
    unique (week_id, team_id, captured_at)
);

create table score_snapshots (
    id uuid primary key,
    matchup_id uuid not null references chaos_matchups(id),
    captured_at timestamptz not null,
    sleeper_payload jsonb not null,
    calculation jsonb not null,
    chaos_score_a numeric(12,4) not null,
    chaos_score_b numeric(12,4) not null
);

create table chaos_standings (
    league_id uuid not null references chaos_leagues(id),
    season integer not null,
    team_id uuid not null references chaos_teams(id),
    wins integer not null default 0,
    losses integer not null default 0,
    ties integer not null default 0,
    points_for numeric(14,4) not null default 0,
    points_against numeric(14,4) not null default 0,
    playoff_seed integer,
    primary key (league_id, season, team_id)
);

-- Append-only source of truth for history, audits, and reconstructing any week.
create table game_events (
    sequence bigint generated always as identity primary key,
    id uuid not null unique,
    league_id uuid not null references chaos_leagues(id),
    week_id uuid references chaos_weeks(id),
    matchup_id uuid references chaos_matchups(id),
    team_id uuid references chaos_teams(id),
    actor_user_id text,
    event_type text not null,
    payload jsonb not null,
    occurred_at timestamptz not null default now(),
    correlation_id uuid,
    causation_id uuid
);

create index ix_game_events_week on game_events (league_id, week_id, sequence);
create index ix_game_events_matchup on game_events (matchup_id, sequence) where matchup_id is not null;

create function prevent_game_event_mutation() returns trigger language plpgsql as $$
begin
    raise exception 'game_events is append-only';
end $$;

create trigger game_events_no_update before update or delete on game_events
for each row execute function prevent_game_event_mutation();

create table commissioner_adjustments (
    id uuid primary key,
    league_id uuid not null references chaos_leagues(id),
    week_id uuid references chaos_weeks(id),
    matchup_id uuid references chaos_matchups(id),
    actor_user_id text not null,
    adjustment_type text not null,
    reason text not null check (length(trim(reason)) >= 5),
    before_value jsonb,
    after_value jsonb not null,
    created_at timestamptz not null default now()
);

commit;
